### ISSUE TITLE
CSV import for AG doesn't handle trailing end-of-line AND doesn't correctly display exception

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#112]
When editing my sample CSV with `vi` - it added a trailing EOL character (thereby making a blank line at the end of file).

This causes an error in the CSV parser - though I think it probably should be possible to safely ignore.

Also, the CSV parser only displayed that error in the javascript console - it wasn't displayed as part of the 'uploader' UI

**Comment by andrewpatto** [comment]
We currently don't have any consistent elsa wide 'visual' pattern for how we display exceptions - so feel free to just get the exception display in red text or something underneath..

We will need to add some sort of standardised ErrorDisplayer component at some point (feel free to have a stab with this issue)

**Comment by mmalenic** [comment]
I had a bit of a shot at this here: 
https://github.com/umccr/elsa-data/blob/0bdd76cf2b664e18ac85ec8dd5bdaaf1a7995cd7/application/frontend/src/components/error-display.tsx#L7-L25
Although we might want to display it in a different way. Maybe with some added red text in a box?

**Comment by andrewpatto** [comment]
[DAC-trailing-line.csv](https://github.com/umccr/elsa-data/files/9999059/DAC-trailing-line.csv)

**Comment by mmalenic** [comment]
So should there be an error/exception box when a trailing EOL is present in the CSV? It could probably just ignore it like you said.

**Comment by mmalenic** [comment]
Wouldn't mind doing this issue by the way! Unless someone else wants it.

**Comment by andrewpatto** [comment]
So yeah I've merged two bugs..

a) I think trailing empty lines should be silently ignored
b) I can think of malformed CSVs though that will cause a real error - and those should be displayed

**Comment by andrewpatto** [comment]
Related #114
