### ISSUE TITLE
Create an external API endpoint that returns a 'release' manifest

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#144]
We have endpoints for generating TSV manifests etc - but all are set up for our internal frontend->backend API (authenticated with session cookies etc).

We also want an API surface that is useable by external parties - and where we will give stronger guarantees of backward compatibility.

First cab off the rank should be an external API that allows the manifest data for a release to be retrieved in JSON.

(this will be useful for say a htsget endpoint)

**Comment by mmalenic** [comment]
By manifest data for a release, do you mean data that is fetched by this api call? https://github.com/umccr/elsa-data/blob/fc947801b18b1b465cfd4ad92c060f534a5ddbcd/application/backend/src/api/routes/release-routes.ts#L418-L451

What would the authentication look like for this? Should it use the same information as the openid login system?

**Comment by andrewpatto** [comment]
Yes - similar in spirit to this - but can contain whatever is needed by htsget in whatever format it needs.

The manifest from that endpoint is TSV just because that's how bioinformaticians like things.

I imagine something that almost mirrors the underlying Edgedb dataset case model

```
[
  { id: "SINGELTONMARY", patients: [
    { id: "MARY": specimens: [
       { id: "HG0001", vcfUrl: "s3:///", bamUrl: "s3:///...", geneRegionsAllowed: [ "HGNC:123", "HGNC:3535" ] }
     ] )
 ]
]
```

For authentication - I'm happy for literally anything at the moment. Seriously, B2b pre shared keys would be fine..

Mutual TLS?

The assumption from Elsa is that htsget is a good actor and that htsget is doing whatever auth it needs.. I mean all Elsa is doing is providing the list of files and id - htsget already has permission to access the data files so its not getting that permission from Elsa

**Comment by mmalenic** [comment]
Yeah that's fair enough. But Elsa would still want to make sure that it is sending the information to htsget and not something else right? Although I guess that doesn't need to be anything super advanced.

**Comment by andrewpatto** [comment]
Yeah that's why something like mutual TLS would be the strongest - as both ends are proving to each other who they are.

But shared secret is fine for the moment
