### ISSUE TITLE
Spike on converting the release page (or subset) to Flowbite react components

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#152]
Rather than inventing our own tailwind css - would be good to have a set of opinionated components.

Given some of our styles were already copied from flowbite it makes sense to try it.

**Comment by andrewpatto** [comment]
I think this ticket is to get it setup - convert a few easy to convert sections - and report back into this ticket some screenshots and a go/no-go assessment for converting the rest of Elsa

**Comment by williamputraintan** [comment]
Founded a bug on `flowbite-react` and when open the [flowbite-react GH](https://github.com/themesberg/flowbite-react) just realized flowbite for react hasn't released yet (despite the [official flowbite docs](https://flowbite.com/docs/getting-started/react/) convinced me enough). 

I think we could still be using the HTML form and convert to a react compatible? Alternative would be [daisyUI](https://daisyui.com/components/), but I am leaning to stick with flowbite. Thoughts?

**Comment by andrewpatto** [comment]
How beta is the unreleased project? I don't mind us starting on a beta (given we aren't in production). As long as it looks like it is expected to be released in the next few months?

**Comment by andrewpatto** [comment]
I mean its your call - just looking now my only worry is that there isn't enough support behind the react versions and that in fact they never really make it to production?

**Comment by andrewpatto** [comment]
Which wouldn't be the end of the world - we can pivot them back to the native HTML classes if we really really had to?

**Comment by williamputraintan** [comment]
Well the one I noticed is about colors that it sometimes works and doesn't (e.g. they are defined on their react docs but the color props in not in the library yet?).

I guess the only advantage of using the react library is to hide most of the lengthy classes defined in the HTML form into a single component. I guess we could try it in but just a note that if this library is still in beta mode.

**Comment by andrewpatto** [comment]
Yeah I think its probably worth it to pick up the pretty much default lengthy classes that we really don't want in our code as we aren't really wanting to customise

**Comment by mmalenic** [comment]
Hmm, flowbite-react really does seem released from the docs, it's only in the github page where it's clear that its not. I think it's okay to use it. At the very least the HTML components are usable, even if something goes wrong with the react ones.
