### ISSUE TITLE
Introduce a service/config that allows Elsa to send emails

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#154]
We will need the ability for Elsa to send notification emails - this ticket is about finding a SMTP client component and having it set up so it can be used (in a wrapped NotificationService?)

https://nodemailer.com/about/

Seems to be a nodejs client appropriate

The config of smtpHost etc will need to be set in the config files

**Comment by andrewpatto** [comment]
We have a SES environment setup in dev so the actual SMTP host etc can easily be put into a config for testing

**Comment by mmalenic** [comment]
What kind of emails will Elsa be sending?
I'm thinking an internal api endpoint that accepts the [message format](https://nodemailer.com/message/) from nodemailer which the backend can just send according to its configuration. That should be as general enough.

**Comment by andrewpatto** [comment]
I would think mainly notification emails ("A new release XYZ has been made in Elsa Data and you are listed as a PI on it.. click here to go to it")

By internal API endpoint - you don't mean a routed API endoint.. just like a method on a service? If so, yes - that probably is a good enough. I mean if we start to notice common email pattersn we can flesh that out then..

**Comment by mmalenic** [comment]
I mean one of these: https://github.com/umccr/elsa-data/blob/fc947801b18b1b465cfd4ad92c060f534a5ddbcd/application/backend/src/api/routes/audit-log-routes.ts#L49-L53 I.e. the same way the frontend has been communicating with the backend for other things. 

Except in the case of an email notification it would probably post a message object.

**Comment by andrewpatto** [comment]
Ok, I'm not sure the frontend will ever be in a position where it is the one deciding to send the emails - would mainly be a backend kind of trigger (i.e. backend to backend).. 

So I was thinking more like this as a starting point..

https://github.com/umccr/elsa-data/blob/fc947801b18b1b465cfd4ad92c060f534a5ddbcd/application/backend/src/business/services/users-service.ts#L20-L59

But 100% along the lines of taking the nodemailer input and merging in the elsa settings in order to set everything up in the service

**Comment by andrewpatto** [comment]
I mean if we did end up adding an email route to the API - it would then essentially be a pass through to the EmailService..

**Comment by mmalenic** [comment]
Ahh okay that makes sense. If it's in the backend then it could just be a function in a service like that. For some reason I thought about a user pressing a button and that sending an email. But the backend could just coordinate that anyway based on whatever triggers it wants.
