### ISSUE TITLE
Resolve IP geolocation as part of ETL for cloudtrail logs

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#162]
It would be useful if the data access audit log also showed the country (and region?) or origin of each IP address.

Rather than defer this to visualisation time - it is probably best to resolve this at ETL phase and just store in the log entry ("AU", "NZ" etc).

**Comment by andrewpatto** [comment]
I know there are a lot of online services that do this (up to some limit for free). And then there are paid services.

And I know that you can get the MaxMind geo lite db downloaded and used for free (well you used to be able to?).

Not sure what the best approach is. Part of me is a bit wary of going off to some external API..

**Comment by williamputraintan** [comment]
Hmmm, thinking of using this [geoip-lite](https://www.npmjs.com/package/geoip-lite) npm package. As you said it download data from MaxMind lite db version.

Had some lookup on external API, which usually had a better information such as city, region, etc but usually have restriction such as query limit per minute.

**Comment by andrewpatto** [comment]
Will need to think about the "optionality' of it as part of the design - because we won't be able to distribute the maxmind db ourselves - and some may not want to create account/download themselves (i.e. they'd chose to disable that functionality).

So possibly Elsa itself just leaves getting the db as part of the deployment - maybe has a config that says "here is the geoip db"?)

And then we do some work on our AWS deployment docker that acqures the db as part of the deployment docker..

**Comment by andrewpatto** [comment]
So happy for this ticket to be based on the assumption that the user has already done the maxmind login and that the db exists somewhere accessible to elsa
