### ISSUE TITLE
[FE] Refine Dataset Detailed Page

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#175]
Currently detailed datasets page only appear as summary box with some JSON dumped on the FE. I suppose it should displayed more records regarding the datasets itself.

**Comment by andrewpatto** [comment]
What do you propose for the details page? I started with a details page because I thought it would be useful - but then couldn't really think of anything to put on it..

So one option is to in fact remove the details page enitrely..

But I figure there *might* be something useful we can display?

**Comment by williamputraintan** [comment]
I am thinking to display datasetsCase and/or datasetsPatient and consents for the dataset. 

1st box is for the dataset summary and consent details (I guess could split out to another box if consent is too complicated to show).

2nd box is for the content of the dataset.

I am thinking for the 2nd box of having a table similar on the release page. I had a bit of drawing of what the table might look like.  
<img width="100" alt="Screen Shot 2023-01-04 at 3 00 39 pm" src="https://user-images.githubusercontent.com/61998484/210482145-91b352ed-2c93-4a2a-9c3f-d08e98437055.png">

Planning to have consent chip is a button and will show a popup/modal to show the consent details, or alternatively  redirect to a consent page.

Thinking for enhancement (not sure if it is necessary):
- Add a search on table, might be just for caseId and patientId. Just to jump from pagination if owner is looking for a particular records.
- Add columns to have a button redirect to artifact page which will show all details on the dataset specimen

Thoughts?



~ Despite I subscribed to this issue, no notif/email was sent from your comment 😐.

**Comment by andrewpatto** [comment]
Some maybe stepping one back - who is the audience for this display? I guess we have to decide if the datasets page is visible to "ordinary" users? 

In the case of a release - all the users who can view the release have been authorised into the data via a DAC - though even those users still don't see patient ids etc unless the data custodian has ticket the corresponding boxes.

So browsing the datasets page - I am doing it in the absence of any actual authorisation? Am I just a user.. am I a data custodian viewing the datasets I control?

**Comment by williamputraintan** [comment]
I am thinking the dataset page is just for the data custodian that they control. 
I don't think it make sense if normal user/researcher would see this?

**Comment by andrewpatto** [comment]
Ok - yep that makes sense - I wasn't clear myself what the audience should be.

What will be the advantage of this grid over (say) what they see in the releases page?
(it seems like it has a fair bit of overlap)

(I do like the idea of the click through to the artifacts - though possibly that is something that we should instead add into the release cases table?)

**Comment by williamputraintan** [comment]
Hmmm, just thinking it gives them widen or an overview on what is actually sync to Elsa for the particular datasets?

Well, eventually searching through RedCap is an option but I thought this might be simpler to read/check? Also I guess could be useful if there is a difference between two dbs on what RedCap and the actual storage (s3) has.

**Comment by andrewpatto** [comment]
Yep - the ability for the data custodians to see what has synced I think is a good use case.

Could the releases 'case' box be retrofitted to serve both use cases? (as in as a react component - and just display it on a different dataset specific page).. maybe with extra columns etc

**Comment by williamputraintan** [comment]
Yes could do! Yeah need to make adjustment because of the checkbox, but I think it could work.

**Comment by andrewpatto** [comment]
I mean only if it makes sense - will leave it to your judgement as to whether the code re-use value outweighs the complexity it might add (I only mentioned it because the list of things you were planning to add had a fair overlap with the existing releases cases code - but that doesn't necessarily mean it isn't worth a new component entirely)
