### ISSUE TITLE
Convert the 10f and cardiac loaders to support trio VCFs in shared files

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#187]
We need to support the ability of a VCF file with 3 subjects in it - to be shared as a single file - but pointed to from 3 different specimens.

The first example of this is in the 10f test data set - where we can see for one of the families we need to create "incorrect" made up paths to the trio VCFS in order that the File records are unique. The correct thing would be to have a single File record for the combined VCF - and we need to store somewhere which "sample id" is then used to fetch the data from the VCF.

This ticket is just about fixing the database modelling/loader for trio VCFs - I don't think this will actually affect any other aspects of the system - but we will make some other tickets regarding how to correctly share the trio files.

As part of this - can we also fix the cardiac loader.

**Comment by williamputraintan** [comment]
> families we need to create "incorrect" made up paths to the trio VCFS in order that the File records are unique

Hmmm, just wondering if linking the multiple dataset patient to the same `lab::ArtifactVCF` would also work?  The problem with the made up 10f data is the [function](https://github.com/umccr/elsa-data/blob/a99dd81b198fa0778620abb70295751267cfee8f/application/backend/src/test-data/insert-test-data-10f-helpers.ts#L69) that handle the trio VCF is always creating a new artifact but we could change this to something like `selectOrCreate` the trio VCF artifact?

**Comment by andrewpatto** [comment]
Yes, whether where we choose to do the merging (Artifact or File) - we will need to fix the insert code to use something like `selectOrCreate` (as you suggest)

**Comment by andrewpatto** [comment]
But I'd think about it first from a model perspective - or what do we want these things to 'mean' (and then worry about how to write the insert code)

Having thought a bit more.. I'm thinking of something like

ArtifactVCF
  vcfFile -> File
  tbiFille -> File
  sampleIds -> String array (??) of all the sample ids mentioned in the VCF

Specimen
  artifact -> ArtifactVCF
  sampleId -> String

??

I think this correctly models the data and intent.. not sure how much in practice it is useful??

**Comment by williamputraintan** [comment]
> ArtifactVCF
vcfFile -> File
tbiFille -> File
sampleIds -> String array (??) of all the sample ids mentioned in the VCF

I think this this one makes more sense since the information sticks to the VCF itself. Initially, I was thinking of having a link/backlink to the DatasetPatient, but I suppose this create dependency between records.
