### ISSUE TITLE
Create a last updated field in each Release

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#188]
There are numerous paths that lead to 'altering' a release.. it might be nice that whatever path that occurs by
(jobs, direct edits etc) - there is a date time field on the Release that is updated to indicate the last update time
(and possibly whoBy?).

I can see how this might be useful in a variety of spots
- reverse sorting the list of 'releases' by which has been touched last
- giving warnings to user or other data owners that someone is editing a release "within the last 15 minutes"

**Comment by DoxasticFox** [comment]
Triggers would be useful for this, but according to their [roadmap](https://www.edgedb.com/roadmap), EdgeDB won't support them until _after_ version 1.0. Alternative solutions include:

* Wrapping EdgeDB's `e.insert` and `e.update` functions to intercept any insertions/updates of `e.release.Release`.
* Patching EdgeDB's autogenerated code to hack-in some our own triggers
* ~Hacking-in triggers using reflection~ (**Edit:** After some more googling, it seems like TypeScript's reflection support is bad.)
* Writing a function called after every relevant insertion or update and explicitly calling it each time

**Comment by andrewpatto** [comment]
At the risk of adding a lot of boilerplatey code, I was just thinking something simple along the lines of explicit calls..

I realise the danger there is that we forget to add the explict calls at all the right spots - but honestly the field/value is more of a UI/nice to have field - rather than something that is critical to data integrity. So accidentally missing a last update is not going to break things..
