### ISSUE TITLE
Web Application Security Checklist

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#196]
- [ ] Broken Access Control
	Currently the application does not check for all API if user is authorise to access datasets/release that belongs to them. This tick should implement authorisation checks, some API may already had a TODO note.
- [x] Apply CSRF token
	The app is using a cookie based authentication and so it is prone to a CSRF attack. Implementing a CSRF token and/or cookie flag to ensure cookie is sent to the same site

**Comment by andrewpatto** [comment]
Removed "[ ] hash release password:" as the intention of the release password is to be a known shared secret amongst a large group of people (who for a short period of time use it for basic unzipping). It is not high security and doesn't need to be hashed.
