### ISSUE TITLE
Use release service to generate TSVs for GCP

### ISSUE THREAD

**Issue by DoxasticFox** [umccr/elsa-data#204]
https://github.com/umccr/elsa-data/pull/186 started adding extensions to the release service to make it keep track of files in a release. Once that's completed, we can use the release service to produce TSVs for the IAM-based sharing introduced in https://github.com/umccr/elsa-data/pull/203.

**Comment by andrewpatto** [comment]
The master manifest generator is now in place. Would like to see a generic

Master manifest -> TSV presigned URLs

with the ability to sign object urls across both GCP and AWS.

But I think this ticket is perhaps also proposing another "GCP IAM" manifest sharing?

**Comment by DoxasticFox** [comment]
>But I think this ticket is perhaps also proposing another "GCP IAM" manifest sharing?

No, the mechanism shouldn't require any significant modifications

**Comment by andrewpatto** [comment]
What would be the advantage of retaining "signed objects" state (speaking to what was in your PR) - rather than just re-signing each time a manifest is requested?
(or is the retaining state needed for the more advanced IAM sharing?)

**Comment by DoxasticFox** [comment]
I guess we should sign it every time. The only drawback I can think of is that it's time-consuming.

There's also a question of whether the 7-day window to use the links should start when the release is activated, or when the manifest is generated. I guess it makes more sense for the timer to start at manifest generation time, right?

>is the retaining state needed for the more advanced IAM sharing?

Nope.

**Comment by andrewpatto** [comment]
The AWS object signing doesn't actually involve any AWS calls - it just literally does some crypto work on the URL string - so for AWS there is no significant performance penalty to regenerated on the fly. Is the GCP object signing different?

The lifespan for 'releases' is possibly in the months i.e. once a release is activated - researchers may still need months at their end to get approval for compute or whatever nonsense their institute makes them go through. So I think the 7 day window is definitely measured from when the signed object manifest is generated

**Comment by DoxasticFox** [comment]
I'm away from my computer right now, but I'm fairly sure gcloud phones home
for each URL to sign

Edit: I take that back. I looked at GCP's signing code and don't see any place where it's doing network stuff, so I don't know ¯\_(ツ)_/¯

**Comment by DoxasticFox** [comment]
Closed by https://github.com/umccr/elsa-data/pull/268
