### ISSUE TITLE
Hand construct a small subset of 1000 genomes but structured as per AG GDR

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#207]
Would be good if we had a test data set (like 10g) - but where it is structured identically to AG GDR.

So I'd go something pretty minimal - pick 10 samples from 1000 genomes (or anywhere tbh - as long as they are public).
Put them into a bucket

umccr-10gdr-data-dev

Then match the folder structure of something like Cardiac - maybe with 2 upload folders (2020-01-01 etc). And then put some files into those folders with matching manifest.

Actually thinking about it - would be good to have some samples with fastqs (HG samples don't).

**Comment by andrewpatto** [comment]
Possibly we construct this inside the AG account - so perhaps that bucket name should be something else..

But that would then mean we could do some real demos of sharing for AG - without accidentally sharing private data.

**Comment by ohofmann** [comment]
Have an upvote.

**Comment by williamputraintan** [comment]
I've added a new bucket (manually) with 2 submissions called `s3://elsa-test-data/` in the AG account.

**Comment by andrewpatto** [comment]
Can you paste in here what the dataset config entry would look like for the new dataset thanks..

**Comment by williamputraintan** [comment]
Sure, the following are the structure of the test data.

The manifest.txt contain the usual checksums, studyIds, and filenames.

```
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ERR013101_1.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ERR013101_2.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ERR016162_1.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/ERR016162_2.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-01-01/manifest.txt

s3://elsa-test-data/FLAGSHIP_A/2020-02-01/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
s3://elsa-test-data/FLAGSHIP_A/2020-02-01/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
s3://elsa-test-data/FLAGSHIP_A/2020-02-01/ERR251112_1.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-02-01/ERR251112_2.fastq.gz
s3://elsa-test-data/FLAGSHIP_A/2020-02-01/manifest.txt

```

**Comment by andrewpatto** [comment]
I meant the config section that would go into the Elsa Data config file..

**Comment by andrewpatto** [comment]
For instance - do we need to set up the corresponding event data store for cloud trail logs etc - and then put the id for that into the config..

**Comment by williamputraintan** [comment]
Arghh, sorry this should be the config.

```
    {
      name: "10GDR",
      description: "A mock AG dataset.",
      uri: "urn:fdc:umccr.org:2023:dataset/10gdr",
      storageLocation: "aws-s3",
      storageUriPrefix: "s3://elsa-test-data",
      aws: {
        eventDataStoreId: "5c021aad-ac9f-4e8c-bae8-b95ecf71c575",
      },
    }
      
```

**Comment by williamputraintan** [comment]
> For instance - do we need to set up the corresponding event data store for cloud trail logs etc - and then put the id for that into the config..

I haven't set up any any cloudTrail lake yet. I'll probably set this up along with a CDK at the infrastructure repo.

**Comment by williamputraintan** [comment]
Updated on infrastructure repo to init deploy of S3Bucket and S3CloudTrailLake set up.

Ref: https://github.com/umccr/infrastructure/pull/285
