### ISSUE TITLE
Convert to using our Release Identifier rather than edge id in all routes/api calls to do with releases

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#212]
We are currently using edge db release id in our react routes and API calls.

However - I think we want to assign a user visible release identifier (e.g "AGRTE3AF") to each release and have that be the main visible identifier as far as the user is concerned. In which cases - I think it would benefit to replace it entirely from front end to back.

I mean we have a getReleaseInfo in the backend - we simply just get it to search by identifier not id - so I don't think this is a massive change.

**Comment by williamputraintan** [comment]
Happy to take this, any pattern specific pattern you had in mind? 
Say `R0001` -  R ='Release', 0001 = the number of releases in Elsa? 
Or, the ID contains a date followed by the releaseNumber? 

Else, probably just had a [Short Unique Id library](https://github.com/simplyhexagonal/short-unique-id) of the length of 10.

**Comment by andrewpatto** [comment]
Yes that looks good - and agree that something short is suitable. Given we have complete control over the db - and can enforce uniqueness in the db - we can maybe even go 8 letters? (we do not need to actually worry about clashes - on clash we can just generate again)

**Comment by andrewpatto** [comment]
Short unique id is what I was talking about there - i think that looks good

**Comment by williamputraintan** [comment]
Yup, just had though that the `R00001`, `R00002` pattern might be super readable here?

**Comment by williamputraintan** [comment]
Thoughts on having the `R0001` style and the number just represent the size of the release in db?

This also could work for datasets say `D0001` therefore the `/dataset` do not need to have the lengthy UUID?

**Comment by andrewpatto** [comment]
The issue with datasets is that they already have a unique id - that is globally consistent and public (the URI).. so they are in a different league to releases (where we assign an identifier locally because we are creating the releases)

I still think we need to do something about the UUIDs for our APIs for datasets - but lets put that in a separate issue

**Comment by andrewpatto** [comment]
Happy with something like `R0001` - but it will need to be able to be set via config (a regex?).

Because I think say the Elsa for AG might want to generate `AGR0001`.. but Garvan might have a different id format they like `garvan.org.au/00001` (or something).

**Comment by andrewpatto** [comment]
So these ids we are generating are not globally unique (because they are short) - and therefore we need to give the organisations the ability to customise them to some extent. (what about if Garvan already had a R0001 that they used for internal record keeping for HR (or something)).

**Comment by williamputraintan** [comment]
> but it will need to be able to be set via config (a regex?).
I am pretty sure you could define in the config. The config can specify the prefix for release ID here and append the rest with current size (+1) from the Db.
