### ISSUE TITLE
Lack of CSRF token is preventing Form post for "Download Zip"

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#233]
We made the "Download Zip" operations to be a special type of form post - in order that the 'save to' download box triggers correctly in the browser. However, this now seems to be failing due to lack of CSRF token.

Need to work out 
- should we just rule these particular routes out of CSRF and what are implications
- should we not do the Form POST technique and deal with download box triggers other way
- can we supply CSRF with Form POST? (best option if possible)

**Comment by williamputraintan** [comment]
> should we not do the Form POST technique and deal with download box triggers other way

I did try with downloading with `axios` converting to a Blob and download it via `<a>` tag. But it doesn't work well, having issue on unzipping and viewing the content.

> can we supply CSRF with Form POST? (best option if possible)

Found a way to put it as a body input and let the hook check on the body.
