### ISSUE TITLE
Slim the Elsa Data docker image

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#243]
We use builders to make sure that we don't need the whole EdgeDb database installed etc..

HOWEVER, I paid no attention to actually what is needed in the base deployable Elsa image. I think it is currently like 1Gb because it is just a standard AWS image. There are lots of techniques (alpine nodejs?) for slim deployable node images.

I'd concentrate on the base first..

THEN - I guess we can also avoid installing all the source code and node_modules (we literally do COPY . .) 

BUT I wouldn't prioritise this.. that can be something for way down the track.. 

My guess is we can get it down to 200MB just by selecting a better base image

**Comment by andrewpatto** [comment]
So basically see if we can slim it via base first and do a PR for that (hopefully like 1hr work).. and then I'll leave this on the backlog for later

**Comment by andrewpatto** [comment]
Any luck with this @mmalenic ? (I know you mentioned).. its not super important - just asking whether to maybe deprioritise - or I can take a crack?

**Comment by mmalenic** [comment]
I gave this a brief look, and simply swapping out AWS image for a `node:18-alpine3.16` didn't seem to improve it much (maybe about 100MB less?).

I'd be happy to look into this more next week, or if you want, feel free to give it a go.

**Comment by andrewpatto** [comment]
Ah ok - I'll have a play.. but if nothing obvious we might just use alpine and call it quits at that! Thanks

**Comment by mmalenic** [comment]
Yeah, I think another big chunk is probably everything being copied in a `COPY . .`, which could probably also be removed.

**Comment by andrewpatto** [comment]
Yep - that's my bad that bit..

**Comment by mmalenic** [comment]
The alpine image does make a bit of a difference (see https://github.com/umccr/elsa-data/compare/dev...refactor/slim-docker-image):
`1.06GB -> 935MB`

It looks like most of the space is tied up in:
```dockerfile
RUN cd backend && npm ci
RUN cd frontend && npm ci
```

E.g.
```sh
docker image history elsa
```
Outputs:
```
...
<missing>      13 minutes ago   RUN /bin/sh -c cd frontend && npm ci # build…   293MB     buildkit.dockerfile.v0
<missing>      13 minutes ago   RUN /bin/sh -c cd backend && npm ci # buildk…   308MB     buildkit.dockerfile.v0
...
```

I guess it's probably the `node_modules`? Maybe these could be pruned.

**Comment by andrewpatto** [comment]
Yeah - the old way I was doing was using esbuild - which prunes the node_modules - and then use the bundled file in the deployed image. But that was playing up with @ decorators for tsyringe. I'll take a run at revisiting that..
