### ISSUE TITLE
Correct TRPC error handling to be on par with existing REST error handling

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#258]
Noticed some issues with errors that occur in backend of TRPC

Had some code failing in backend (always a possibility) - and that correctly errored out the TRCP mutation..

However - nothing was logged in the backend - where I would expect at the minimum all errors in "services" are trapped/logged and passed through.. (not by adding catch clauses, by using the fastify/trcp hooks)

*Also* TRPC has a completely custom error code mechanism. Need to think if instead we want to translate these to the RFC7807 error format that we are using for our regular REST apis (it is possible to do error shapes in TRPC so I think this would be relatively straightforward - though possibly not bother?)

**Comment by andrewpatto** [comment]
I mean TRPC thinks it has an error handler slot - it just wasn't clear to me where this hook lives against the fastify backend..

https://trpc.io/docs/server/error-handling

```
export default trpcNext.createNextApiHandler({
  // ...
  onError({ error, type, path, input, ctx, req }) {
    console.error('Error:', error);
    if (error.code === 'INTERNAL_SERVER_ERROR') {
      // send to bug reporting
    }
  },
});
```

**Comment by andrewpatto** [comment]
I asked ChatGPT - and it gave me enough of a clue to hunt it down.. turns out onError is one of the Fastifyoptions

From inside the fastify request handler

```
const result = await resolveHTTPResponse({
    req,
    createContext,
    path: opts.path,
    router: opts.router,
    batching: opts.batching,
    responseMeta: opts.responseMeta,
    onError(o) {
      opts?.onError?.({ ...o, req: opts.req });
    },
  });
```

So I think that implies..

```
await this.server.register(fastifyTRPCPlugin, {
      prefix: "/api/trpc",
      trpcOptions: { router: appRouter, createContext, onError: ERROR HANDLER HERE },
    });
```

**Comment by andrewpatto** [comment]
There's a type `TrpcError` that is the error handler type - though the typescript types for trpc do my head in so I'll leave that as an exercise for someone else

**Comment by DoxasticFox** [comment]
Is this my reward for always whinging about things not being typed properly? 😂

**Comment by andrewpatto** [comment]
I've added an integration test of TRPC doing successful calls, and unauthenticated calls..

With a couple of TODOs for where tests might go for how errors are handled

**Comment by andrewpatto** [comment]
So to be clear - number one priority is the get the server backend noticing 500 errors that occur in TRPC routes and at least logging them.

But then there might be some interesting things looking at how TRPC errors are reflected out to the frontend - and whether we need to unify around 7807 (or maybe not)
