### ISSUE TITLE
Do a E2E selecting two members of a trio and then downloading pre-signed URL manifest zip

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#283]
Testing
- support for multi member VCFs
- presigning (the actual links do not have to be downloadable! just that they are vaguelly well formed - we'll have fake ACCESS keys in the test suite config anyhow)
- basic release manifest

**Comment by andrewpatto** [comment]
btw this will need to be a test that does the setup from the release administrator end - and then logs in as a member or manager and does the download (now that the UI is split - the download links are no longer available to the release administrator)

**Comment by williamputraintan** [comment]
I am trying to test whether the downloaded manifest contain an AWS presigned URL but it seems to be challenging as it is guarded with password encrypted aes256. Managed to try with [unzipper](https://github.com/ZJONSSON/node-unzipper) but it doesn't support aes256 decryption. So I am thinking whether the file downloaded have the proper name would be sufficient for the e2e testing here?

`https://github.com/ZJONSSON/node-unzipper/issues/86`

**Comment by andrewpatto** [comment]
Can you get the test to just shell out for an unzip? (I mean its just a test - so we have some control over the underlying base machine to ensure it has the right zip)

**Comment by williamputraintan** [comment]
Yup, also tried with `unzip` from shell but have an incompatible error thrown.


```
wpintan@5690L-205576-M:~/UMCCR/GitHub/elsa-data/e2e [12:36:42]% unzip -P "abcd" -d ./test-results/tmp/ ./test-results/tmp/manifest.zip 
Archive:  ./test-results/tmp/manifest.zip
   skipping: manifest.tsv            need PK compat. v5.1 (can do v4.5)
```

From https://unix.stackexchange.com/a/183453 , it is suggested to use the 7zip instead so if go this route might need the GH action depends on this?

**Comment by williamputraintan** [comment]
> support for multi member VCFs

Question on this point here, do you mean testing to edit patients in the Cases box? @andrewpatto

**Comment by andrewpatto** [comment]
No I mean if there is a single VCF with 3 patients - and 2 are selected - do we end up with two rows in the TSV (both with the same signed VCF) (I mean that's the best we can do at the moment).

I just think its an interesting edge case so is worthy of a test..

If we implement something amazing functionality wise re: multi member VCFs - then we'll need to update the e2e test for whatever we implement..

at the moment more interested in a test to prove we don't crash!
