### ISSUE TITLE
Work out if pre-signed S3 URLs can be tracked in CloudTrail back to the session that made them

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#3]
Assume we have a service that has the right AWS permissions to a bucket and is asked to generate a set of 10 presigned S3 URLs.

Then next week - the service gets asked to generate the same set again.

Assuming we can save anything we want locally (access keys etc) - can we go through the cloud trail data lake and work out how much/which data was accessed from each 'sharing'.

I am assuming that the userIdentity of the cloud trail event is enough to distinguish between.. but would be good to confirm.

https://github.com/awsdocs/aws-cloudtrail-user-guide/blob/master/doc_source/cloudtrail-event-reference.md

The idea would be that whenever Elsa generates a file of presigned URLs - we would track when and for who.. and then Elsa could regularly drag across from CloudTrail some summary stats of how the urls were actually used (amount downloaded, when, ip address ranges?)

**Comment by williamputraintan** [comment]
I think your assumption is pretty much correct.

I did have a try on cloudtrail and it does give you quite detailed event load on who accessed it and what event type is invoked. `userIdentity` does record all the credentials used for the pre-signed url, and contain the access key used to generate the pre-signed. I guess in this case for every single pre-signed url request needed to generate a different access key so that we could distinguish them.

The payload also includes the number of bytes being transferred in/out based from that event. The number of byte is calculated when the event is finished. So if in the middle of downloading is cancelled, it will record the bytes transferred out until that point. Multipart download would end up into multiple event which will also spread the bytes transferred out accordingly. 

Payload example for cloudtrail: 
```
{
  "Records": [
    {
      "eventVersion": "1.08",
      "userIdentity": {
        "type": "AssumedRole",
        "principalId": "XXXXXXXXXXXXXX:john.doe@umccr.org",
        "arn": "arn:aws:sts::843407916570:assumed-role/AWSReservedSSO_PowerUserAccess_gA9S2jRXrQgA9S2/john.doe@umccr.org",
        "accountId": "843407916570",
        "accessKeyId": "ASIAXXXXXXXXXXXXXX",
        "sessionContext": {
          "sessionIssuer": {
            "type": "Role",
            "principalId": "XXXXXXXXXXXXXX",
            "arn": "arn:aws:iam::843407916570:role/aws-reserved/sso.amazonaws.com/ap-southeast-2/AWSReservedSSO_PowerUserAccess_gA9S2jRXrQgA9S2",
            "accountId": "843407916570",
            "userName": "AWSReservedSSO_PowerUserAccess_gA9S2jRXrQgA9S2"
          },
          "attributes": {
            "creationDate": "2022-06-20T05:56:15Z",
            "mfaAuthenticated": "false"
          }
        }
      },
      "eventTime": "2022-06-20T06:22:16Z",
      "eventSource": "s3.amazonaws.com",
      "eventName": "GetObject",
      "awsRegion": "ap-southeast-2",
      "sourceIPAddress": "123.12.12.123",
      "userAgent": "[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36]",
      "requestParameters": {
        "X-Amz-Date": "20220620T062200Z",
        "bucketName": "temp-dev",
        "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
        "X-Amz-SignedHeaders": "host",
        "Host": "temp-dev.s3.ap-southeast-2.amazonaws.com",
        "X-Amz-Expires": "3600",
        "key": "john/sample.txt"
      },
      "responseElements": null,
      "additionalEventData": {
        "SignatureVersion": "SigV4",
        "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "bytesTransferredIn": 0.0,
        "AuthenticationMethod": "QueryString",
        "x-amz-id-2": "IwdmY+qMAsIWFUrJqs6mhBxsxG7Wv3iklnYC12gjoasdhn=",
        "bytesTransferredOut": 24834700
      },
      "requestID": "NMED4VXGER9MJ7KK",
      "eventID": "bcdb96c6-170f-47ed-8fce-961a81d2c4ff",
      "readOnly": true,
      "resources": [
        {
          "type": "AWS::S3::Object",
          "ARN": "arn:aws:s3:::temp-dev/john/sample.txt"
        },
        {
          "accountId": "843407916570",
          "type": "AWS::S3::Bucket",
          "ARN": "arn:aws:s3:::temp-dev"
        }
      ],
      "eventType": "AwsApiCall",
      "managementEvent": false,
      "recipientAccountId": "843407916570",
      "eventCategory": "Data",
      "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "temp-dev.s3.ap-southeast-2.amazonaws.com"
      }
    }
  ]
}

```

`CloudTrail lake` would end up the same payload just that nested json will be converted to one line JSON string (as it is represented in SQL form).

> The idea would be that whenever Elsa generates a file of presigned URLs - we would track when and for who.
This should work, we could use the sdk to query these records out.

**Comment by andrewpatto** [comment]
Excellent.. thanks for that. So lets assume was are running in Fargate (with an implied AWS identity/role letting us 'do' things).

If we wanted each 'presign' set to be unique - we could presumably ask for a new IAM session - within the existing Fargate role?

Or is asking for a session that is just the same as the existing session basically a no-op?

That would then allow us to control the 'uniqueness' of the session credentials that are used to generate each pre-signed set.

**Comment by andrewpatto** [comment]
TBH - I've never quite understood the assume-role session from within an assumed-role session..
