### ISSUE TITLE
Audit entry backend should use unified query

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#326]
There is now a unified query mechanism for audit events.. BUT - it cannot do "ORDER BY" with the same granularity as the typescript version. In particular - there is no way to pass in as a param the ASC or DESC aspect of an order..

Might need a discussion in the EdgeDb boards - cos maybe I am just missing something..

So once we have a single function - we can replace a lot of the backend Audit entry service methods.

**Comment by andrewpatto** [comment]
@mmalenic - did you end up doing this already? If not, can you take a look at some point. I know the technique for selectively changing the ordering (i.e. order by name or order by id).. but i can't work out how to parametrise the ASC or DESC.. (without doing a literal string substitiution on the query text)

**Comment by mmalenic** [comment]
I haven't had a look at this yet - happy to do so if you like. Although, I do worry that the only way will be a string substitution, which isn't ideal...

**Comment by andrewpatto** [comment]
Elvis in the edgedb discord seems to have pasted in this snippet in June

```
order by (.prop1 if sortProperty = 'prop1' and sortDirection = 'asc' .. else '') asc then  (.prop1 if sortProperty = 'prop1' and sortDirection = 'desc' .. else '') desc
```

**Comment by andrewpatto** [comment]
https://discord.com/channels/841451783728529451/1116112184351674438
-
