### ISSUE TITLE
AG import should extract sample ids from filenames if given regex

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#328]
The file paths for objects often have a specimen/sample id in them - according to the rules of the lab that did the sequencing. We should allow the dataset config to define a regex (i.e. a capture group) that if matches defines the specimen id.

**Comment by andrewpatto** [comment]
VCGS samples (for instance) have a pattern 00W000000 that could easily be extracted. Our 10G datasets have a pattern of HG00000 that could also be extracted. That would allow the UI to at least display something for specimen id.

**Comment by williamputraintan** [comment]
Adding to this I suppose this also could add the DatasetCase Id regex configurable from the config file.

Currently this is the FamilyId gotten regex from `FAM\d+` from the filename as well.

**Comment by andrewpatto** [comment]
Yes its possible we could make all the magic strings of the algorithm be configurable from the dataset config..
