### ISSUE TITLE
Frontend Responsiveness

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#330]
Many UI component (mostly tables) is overlapping on smaller screen. I think we should sort this out for our MVP.

**Comment by andrewpatto** [comment]
Agree with a need to fix - am reasonably happy if its a half arse job though (see the releases table where we just basically drop some columns).

I don't think the "usual" pattern for usage of the tool my AG will be on their phones.. so I am happy if the table display is just less functional..
