### ISSUE TITLE
Move Maxmind DB stuff out of Elsa itself - but allow it to be down as part of Deploy docker builds

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#333]
Elsa itself can never really deploy an image that has the Maxmind IP database in it - currently it is setup so it can do a download on startup - but I'm not super happy with that.

I think the correct place is in deployment - where someone can take the Elsa base image and easily add in whatever Maxmind db they have (either public or licensed).

So we just need to show how that might be done in the AG demo deploy - with probably the current config settings in Elsa good enough to handle setting the path to where it appears in the docker image.

**Comment by williamputraintan** [comment]
I suppose then the IP lookup would follow similar pattern to have the maxmind-db [paste next to the dataset.json5](https://github.com/umccr/elsa-data-aws-deploy/blob/6c108c0d35b3d5151ffba8fff3500dcf11c87d79/artifacts/elsa-data-application-deployment-ag-demo-docker-image/Dockerfile#L7-L8)?

**Comment by andrewpatto** [comment]
Yeah - the sourcing the maxmind file can be a problem for the Docker construction.. not a problem inside Elsa..

In our specific UMCCR builds for AG demo (for instance) - we can literally "fetch from S3".. or require it to be copied in by the build server etc to make it available for the Dockerfile. i.e. we can build it ourselves without emvbedding a maxmind db in the github repo

**Comment by andrewpatto** [comment]
And I think that is the best approach for general use - who knows how corporations who actually pay for maxmind might store the database and where. This gives them the flexibility to just need to slot it into a docker layer somehow..
