### ISSUE TITLE
Use DaisyUI for errors

### ISSUE THREAD

**Issue by mmalenic** [umccr/elsa-data#336]
It would be good to use the same DaisyUI themes for displaying errors as the rest of the front-end. I think errors would also look better if they were rendered as red alert boxes, similar to the "editing release" alert warning.

Should all errors be rendered at the top of the page, below the navigation bar if possible? Even if those errors originated in a box somewhere else?

**Comment by andrewpatto** [comment]
can you mock up an example on one page and paste in a screenshot here.. I think it sounds good - just worried about us losing the locality of the error

**Comment by andrewpatto** [comment]
Also, we have lots of cases where we seem to have both a Box error - *and* an ErrorBoundary error - often with the same error message (also, often copy/pasted with differing but incorrect error messages). Is there a way to unify that so that the releases page/box only has one Error component? (possibly that also fits in better with a singly daisy ui at the top?)

**Comment by mmalenic** [comment]
Yeah, I was thinking it would be easier to unify the ErrorBoundary when there is only one spot that it can occur.

**Comment by mmalenic** [comment]
I think this would also be okay because the alert can grab the user's attention and scroll the view up?

**Comment by andrewpatto** [comment]
> I think this would also be okay because the alert can grab the user's attention and scroll the view up?

Yes - but the risk is the user has lost the link to what is _causing_ the error.. so some refetch of the something fails and the user sees "release query failing" - but there's 3 large cards on the page so they are not sure what it is that is triggering the error.. that said, I'm not sure I mind - I think it depends on what sort of errors it is used for and how it is done.

**Comment by mmalenic** [comment]
Yeah that's a good point. I think it's difficult to separate errors that a user can do something about, and errors that they can't do anything about, such as a refetch failing.

**Comment by mmalenic** [comment]
For example, something like this:
![image](https://github.com/umccr/elsa-data/assets/53923960/a017ddd4-66b5-41af-a15c-08df34935839)

This could be either on the top-level page, or in the box itself (this error originates from clicking "apply all").

I think the alert is probably the best for minimal information - if there is anything more than 1 or 2 lines its probably too crowded. This might make it difficult to render the full 7807Error information? Although I'm not sure that it's all needed anyway.

**Comment by andrewpatto** [comment]
Yeah that looks good. I'm not so worried about displaying *all* the 7807 error info to the user in the UI.. maybe dump the whole error 7807 json to the Javascript console? But only display the detail in the UI?

Also, I wouldn't put the word detail .. just the title and text is fine..

**Comment by mmalenic** [comment]
Do you think some of these alerts should be rendered in a box, rather than top-level? For example, if there is an error adding a user in the "User Management" page after clicking "Add/Update", then maybe this error would be best in the box itself?

**Comment by andrewpatto** [comment]
Yes - I like the aspect where the the direct error from something like "Add/Update" appears local to the card/box.

I don't like us repeating the "error in release query" text with a second Error boundary - given how often they seem to get out of sync.

So if we can identify the error as occurring _within_ the context of a box/card - happy for it to display a purposeful error message in that box.

And then catch everything else with a top level boundary check (caught outside the page itself)?
