### ISSUE TITLE
UI issues on audit page

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#344]
![Screenshot 2023-05-17 at 12 58 32 pm](https://github.com/umccr/elsa-data/assets/1973827/3984daeb-5ef3-48e5-91d2-1a222476d0ec)

The dropdown checkbox filters is a bit different from anything else - and I don't think it transitions well when we start to add other filters ("Outcome filter") as those don't really fit into a dropdown.

Suggesting we get rid of the dropdown entirely and just have a space above the table with regular daisy controls (which will currently just be the checkboxes)

Also, for some reason - I thought I put an overall query load cursor on the table - so that when you hit the page initially you'd see a loader cursor. But it doesn't seem to be appearing so I must have done something wrong.

**Comment by andrewpatto** [comment]
Possible to save this one up until #326 - and introduce more broad filtering at the same time..
(Description "starts with".. Outcome.. Category..)

**Comment by mmalenic** [comment]
Were you thinking something like this?
![image](https://github.com/umccr/elsa-data/assets/53923960/a1d11325-2d60-40c7-9d78-fe76f2c84d04)

**Comment by andrewpatto** [comment]
Kind of - but even more of a drop of the checkboxes.. (so not even wedged into the Audit Event header tow).

I just think we're going to be adding to that filter list (Description search etc - so not just the 4 existing checkboxes) - and eventually that is not going to fit. So I mean to promote it to something in between "Audit Events" header and the table itself.

Its not like we are hard up for space vertically on our screens (the user can already set the number of rows to display)..

**Comment by andrewpatto** [comment]
Also - I'm not sure about the "All audit events" - I mean I understand it, but it is a category not the same as the other 3. Possibly we could have a separate "all/none" kind of checkbox thing given we have more space to make a better UI.

**Comment by mmalenic** [comment]
Hmm, yes, I see what you mean. To make the all/none checkbox different it could be a toggle?

**Comment by mmalenic** [comment]
Another approach would be to have buttons that are active until they are clicked again. This could be good for adding filters dynamically, e.g. a box with something like "outcome:success" and a close button on it. Although I don't know if this would be too bulky if the user decides to add a lot of filters.

**Comment by andrewpatto** [comment]
Yes - eventually a proper complete filter mechanism needs all those - because filtering for an empty string is not the same as not wanting that particular filter at all. 

In fact I think the modern one is to give them a palette of filter creation options - and then they can add "badges" (?) where each badge is like "description has 'login'".. "age > 50 days" etc

**Comment by andrewpatto** [comment]
I mean redoing all this might be best put off until we have a handle on #326

**Comment by mmalenic** [comment]
Yep, that's fair. I'll make the minor changes suggested here, and the others can be after #326.
