### ISSUE TITLE
William Permissions Bug Hunt June 2023

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#367]
- [x] ~Admin and~ SuperAdmin should not have access to edit the copy-out bucket name (this should include to guard the API)
- [x] AccessData box should reflect to the config and Data Sharing Control
- [x] When box is disabled (which means `sepia` theme is applied), some text-box/input is still editable
- [x] API for release modification is not guarded with userRole checks (and perhaps also enforce the audit entry when modifying release)

**Comment by andrewpatto** [comment]
Umm.. not sure about this..

I think there is a scenario where the Release admins get this information out of band.. (i.e the researcher doesn't even know what a bucket is - and for instance they just forward on an email from their IT dept)

Or it occurs in Slack..

not ideal - but I can see the info going straight to the AG staff

**Comment by williamputraintan** [comment]
I suppose at least SuperAdmin shouldn't allow to edit this?

**Comment by andrewpatto** [comment]
Yes - definitely not SuperAdmins

**Comment by andrewpatto** [comment]
SuperAdmins shouldn't *ever* be given extra rights than their normal perms - *except* for in the user management page

**Comment by williamputraintan** [comment]
Adding to this ticket, I think there is a disconnected / wrong logic for what is showing in the `Access Data` box? As the config don't have access-point / gcp-sharing but the member could see everything?

![Screenshot 2023-06-22 at 10 23 53](https://github.com/umccr/elsa-data/assets/61998484/7d5093ea-76f4-49e8-87d9-96f5b4668c1b)

**Comment by andrewpatto** [comment]
Ah yes - good point.. I didn't notice that in AG demo because I've switched off all but the enabled sharers..

So yes - we need to get the "Access Data" list to be dynamic in what it shows (all the data for that should be present - I think it might just need some React switches)
