### ISSUE TITLE
Import a cardiac flagship Redcap CSV into Elsa as a new 'release'

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#38]
@sarahcasauria has said we can get an export out of the AG data access control system in some CSV/TSV/JSON format (TBD) and we should give some UI mechanism by which that can be specified and new releases are detected and able to be created in Elsa.

I am considering this UI flow to be like the following (but happy for other thoughts)

A new tab in the import release panel (alongside REMS/DUO) - something like "Australian Genomics Export".

Then on that tab would be a "drag TSV/CSV file here" (any sort of file chooser - but there's heaps of nice react drag-drop/select ones available).

The TSV/CSV would be analysed in react (the file will be small) - and a picker modal dialog displayed (see what happens with the REMS one). The user would then pick which of the ones in the TSV they want to 'create' (we can think about batch in the future - for the moment one by one is ok I think - but feel free to do batch if easy)

The one chosen would then initiate a "Create release" POST(?) API call telling it to fill in a new Release database entry.

The main work here I guess will be determining what is available in the Redcap export and how best it maps across. It may require actual changes to the Release schema. And then working on the specific JSON API schemas needed to support the 'create release' api call.

I wouldn't worry overly about permission structures at the moment - we still need to sort out a role/admin (who can do this operation?) - so we can add those boundaries later. For the moment just go with "everyone logged in" can do this..

**Comment by andrewpatto** [comment]
Sarah is away on leave till 19th September - but would like this to be started asap once she is back (at least starting with a sample CSV extract and fleshing out a flow even if not perfect).

**Comment by sarahcasauria** [comment]
@andrewpatto I have returned from leave and can work on this task asap. Could you remind me what type of data you are looking to extract from REDCap for this purpose? Is this process related to the "picking eligible participants" stage of the data curation process?

**Comment by andrewpatto** [comment]
Hi @sarahcasauria (sorry for the delay - I was away too!). For this task - I am looking to extract the 'approved applications' level of data. So for each approved application - some sort of id, title of the application, emails of the researchers etc.

So for this extract - not the individual participant level of detail.

**Comment by andrewpatto** [comment]
The CSV that would come out of Redcap (from Sarah via email)

[DAR form raw.csv](https://github.com/umccr/elsa-data/files/9770875/DAR.form.raw.csv)

**Comment by andrewpatto** [comment]
I have transposed this (and with the nice names excel)


| Nice Name                                                                                                                   | CSV Field Name                 | Example 1                        | Example 2           |
|-----------------------------------------------------------------------------------------------------------------------------|--------------------------------|----------------------------------|---------------------|
| Application number:                                                                                                         | daf_num                        | 1                                | 2                   |
| Application date:                                                                                                           | application_date_hid           | 1/1/2022                         | 23/4/2021           |
| Has this project received ethical approval?                                                                                 | daf_hrec_approve               | 1                                | 1                   |
| Please upload the ethics approval letter for this project                                                                   | daf_ethics_letter              | File.pdf                         | ethics.pdf          |
| Please provide your ethics application number for this project                                                              | daf_hrec_num                   | 123456                           | 456789              |
| Date of ethics approval:                                                                                                    | daf_hrec_approve_dt            | 1/1/2022                         | 3/2/2020            |
| Project Title:                                                                                                              | daf_project_title              | Test Project 1                   | Test project 2      |
| Project public summary                                                                                                      | daf_public_summ                | Project summarising              | Project summarising |
| Type of research (please select all that apply): (choice=Methods development and validation studies (DUO:0000031))          | daf_type_research___method_dev | 1                                | 0                   |
| Type of research (please select all that apply): (choice=Controls for case control studies (DUO:0000036))                   | daf_type_research___case_ctrl  | 0                                | 0                   |
| Type of research (please select all that apply): (choice=Population structure studies (DUO:0000032))                        | daf_type_research___popn_stud  | 1                                | 1                   |
| Type of research (please select all that apply): (choice=Health / Medical / Biomedical research (DUO:0000006))              | daf_type_research___hmb        | 0                                | 0                   |
| Type of research (please select all that apply): (choice=Population origins or ancestry research (DUO:0000033))             | daf_type_research___poa        | 1                                | 0                   |
| Type of research (please select all that apply): (choice=Disease related studies (DUO:0000007) {daf_type_research_disease}) | daf_type_research___disease    | 0                                | 1                   |
| Type of research (please select all that apply): (choice=Other {daf_type_research_oth})                                     | daf_type_research___other      | 1                                | 0                   |
| Flagships of interest (choice=Cancer Flagship(s))                                                                           | daf_flagships___cancer         | 1                                | 0                   |
| Flagships of interest (choice=Rare Diseases Flagship(s))                                                                    | daf_flagships___rare           | 1                                | 1                   |
| Flagships of interest (choice=General Population Cohort(s))                                                                 | daf_flagships___genpop         | 0                                | 0                   |
| Rare disease flagships (choice=Acute Care Genomics)                                                                         | daf_flagships_rd___ac          | 1                                | 0                   |
| Rare disease flagships (choice=Brain Malformations)                                                                         | daf_flagships_rd___bm          | 0                                | 1                   |
| Rare disease flagships (choice=Cardiovascular Disorders)                                                                    | daf_flagships_rd___cardio      | 1                                | 0                   |
| Rare disease flagships (choice=Epileptic Encephalopathy)                                                                    | daf_flagships_rd___ee          | 0                                | 0                   |
| Rare disease flagships (choice=HIDDEN Renal Genetics)                                                                       | daf_flagships_rd___hidden      | 1                                | 1                   |
| Rare disease flagships (choice=Genetic Immunology)                                                                          | daf_flagships_rd___gi          | 0                                | 0                   |
| Rare disease flagships (choice=Intellectual Disabilities)                                                                   | daf_flagships_rd___id          | 1                                | 0                   |
| Rare disease flagships (choice=Interstitial or Diffuse Lung Disease)                                                        | daf_flagships_rd___lung        | 0                                | 1                   |
| Rare disease flagships (choice=KidGen Renal Genetics)                                                                       | daf_flagships_rd___renal       | 1                                | 0                   |
| Rare disease flagships (choice=Leukodystrophies)                                                                            | daf_flagships_rd___leuko       | 0                                | 0                   |
| Rare disease flagships (choice=Mitochondrial Diseases)                                                                      | daf_flagships_rd___mito        | 1                                | 1                   |
| Rare disease flagships (choice=Neuromuscular Disorders)                                                                     | daf_flagships_rd___nmd         | 0                                | 0                   |
| Cancer flagships (choice=Acute Lymphoblastic Leukaemia)                                                                     | daf_flagships_cancer___all     | 1                                | 0                   |
| Cancer flagships (choice=Hereditary Cancer Syndromes (ICCon))                                                               | daf_flagships_cancer___iccon   | 0                                | 0                   |
| Cancer flagships (choice=Somatic Cancer (iPREDICT))                                                                         | daf_flagships_cancer___somatic | 1                                | 0                   |
| Cancer flagships (choice=Lung Cancer EBUS-TBNA)                                                                             | daf_flagships_cancer___lung    | 0                                | 0                   |
| General Population flagships (choice=Mackenzies Mission)                                                                    | daf_flagships_genpop___mm      | 0                                | 0                   |
| Data types requested (choice=FASTQs)                                                                                        | daf_file_types___fastq         | 1                                | 1                   |
| Data types requested (choice=BAMs)                                                                                          | daf_file_types___bams          | 1                                | 1                   |
| Data types requested (choice=VCFs)                                                                                          | daf_file_types___vcfs          | 1                                | 1                   |
| Data types requested (choice=Phenotypic/Clinical Data)                                                                      | daf_file_types___phensurvey    | 1                                | 0                   |
| Data types requested (choice=Participant Survey Data)                                                                       | daf_file_types___selfsurvey    | 0                                | 0                   |
| Data types requested (choice=Participant Contact Details)                                                                   | daf_file_types___contact       | 0                                | 0                   |
| Phenotypic/Clinical data categories requested (choice=Demographics (e.g. age, sex, etc.))                                   | daf_clindata_category___1      | 1                                | 0                   |
| Phenotypic/Clinical data categories requested (choice=Ethnicity)                                                            | daf_clindata_category___2      | 0                                | 0                   |
| Phenotypic/Clinical data categories requested (choice=Family History)                                                       | daf_clindata_category___3      | 0                                | 0                   |
| Phenotypic/Clinical data categories requested (choice=Clinical investigations)                                              | daf_clindata_category___4      | 1                                | 0                   |
| Phenotypic/Clinical data categories requested (choice=Variant information)                                                  | daf_clindata_category___5      | 1                                | 0                   |
| Flagship set requested                                                                                                      | daf_data_req                   | 2                                | 1                   |
| Describe the subset of participants you are requestingNote: Do NOT input any identifying information into this field        | daf_data_req_subset            | Participants with cardiomyopathy |                     |
| Title                                                                                                                       | daf_applicant_title            | Prof                             | Dr                  |
| Full Name                                                                                                                   | daf_applicant_name             | Albus Dumbledore                 | Meredith Grey       |
| Institution                                                                                                                 | daf_applicant_institution      | Hogwarts                         | Grey Sloan Hospital |
| Email address                                                                                                               | daf_applicant_email            | albus.dumbledore@test.com        | meredith@grey.com   |
| Is the applicant the Principal Investigator for this project?                                                               | daf_applicant_pi_yn            | 1                                | 0                   |
| Principal Investigator name                                                                                                 | daf_pi_name                    |                                  | Christina Yang      |
| Is the Principal Investigator located at the same institution as the applicant?                                             | daf_pi_institution_same        |                                  | Yes                 |
| Principal Investigator institution                                                                                          | daf_pi_institution             |                                  |                     |
| Principal Investigator email address                                                                                        | daf_pi_email                   |                                  | christina@yang.com  |
| Number of collaborating sites/institutions                                                                                  | daf_collab_num                 | 1                                | 0                   |
| 1. Site name                                                                                                                | daf_institution_site1          | Durmstrang                       |                     |
| 1. Contact person                                                                                                           | daf_contact_site1              | Igor Karkaroff                   |                     |
| 1. Contact person email                                                                                                     | daf_contact_email_site1        | igor@durmstrang.org              |                     |
| 1. Will this site be housing requested data?                                                                                | daf_data_house_site1           | 1                                |                     |
| 2. Site name                                                                                                                | daf_institution_site2          |                                  |                     |
| 2. Contact person                                                                                                           | daf_contact_site2              |                                  |                     |
| 2. Contact person email                                                                                                     | daf_contact_email_site2        |                                  |                     |
| 2. Will this site be housing requested data?                                                                                | daf_data_house_site2           |                                  |                     |
| 3. Site name                                                                                                                | daf_institution_site3          |                                  |                     |
| 3. Contact person                                                                                                           | daf_contact_site3              |                                  |                     |
| 3. Contact person email                                                                                                     | daf_contact_email_site3        |                                  |                     |
| 3. Will this site be housing requested data?                                                                                | daf_data_house_site3           |                                  |                     |
| 4. Site name                                                                                                                | daf_institution_site4          |                                  |                     |
| 4. Contact person                                                                                                           | daf_contact_site4              |                                  |                     |
| 4. Contact person email                                                                                                     | daf_contact_email_site4        |                                  |                     |
| 4. Will this site be housing requested data?                                                                                | daf_data_house_site4           |                                  |                     |
| 5. Site name                                                                                                                | daf_institution_site5          |                                  |                     |
| 5. Contact person                                                                                                           | daf_contact_site5              |                                  |                     |
| 5. Contact person email                                                                                                     | daf_contact_email_site5        |                                  |                     |
| 5. Will this site be housing requested data?                                                                                | daf_data_house_site5           |                                  |                     |
| 6. Site name                                                                                                                | daf_institution_site6          |                                  |                     |
| 6. Contact person                                                                                                           | daf_contact_site6              |                                  |                     |
| 6. Contact person email                                                                                                     | daf_contact_email_site6        |                                  |                     |
| 6. Will this site be housing requested data?                                                                                | daf_data_house_site6           |                                  |                     |
| 7. Site name                                                                                                                | daf_institution_site7          |                                  |                     |
| 7. Contact person                                                                                                           | daf_contact_site7              |                                  |                     |
| 7. Contact person email                                                                                                     | daf_contact_email_site7        |                                  |                     |
| 7. Will this site be housing requested data?                                                                                | daf_data_house_site7           |                                  |                     |
| 8. Site name                                                                                                                | daf_institution_site8          |                                  |                     |
| 8. Contact person                                                                                                           | daf_contact_site8              |                                  |                     |
| 8. Contact person email                                                                                                     | daf_contact_email_site8        |                                  |                     |
| 8. Will this site be housing requested data?                                                                                | daf_data_house_site8           |                                  |                     |
| 9. Site name                                                                                                                | daf_institution_site9          |                                  |                     |
| 9. Contact person                                                                                                           | daf_contact_site9              |                                  |                     |
| 9. Contact person email                                                                                                     | daf_contact_email_site9        |                                  |                     |
| 9. Will this site be housing requested data?                                                                                | daf_data_house_site9           |                                  |                     |
| 10. Site name                                                                                                               | daf_institution_site10         |                                  |                     |
| 10. Contact person                                                                                                          | daf_contact_site10             |                                  |                     |
| 10. Contact person email                                                                                                    | daf_contact_email_site10       |                                  |                     |
| 10. Will this site be housing requested data?                                                                               | daf_data_house_site10          |                                  |                     |
| 11. Site name                                                                                                               | daf_institution_site11         |                                  |                     |
| 11. Contact person                                                                                                          | daf_contact_site11             |                                  |                     |
| 11. Contact person email                                                                                                    | daf_contact_email_site11       |                                  |                     |
| 11. Will this site be housing requested data?                                                                               | daf_data_house_site11          |                                  |                     |
| 12. Site name                                                                                                               | daf_institution_site12         |                                  |                     |
| 12. Contact person                                                                                                          | daf_contact_site12             |                                  |                     |
| 12. Contact person email                                                                                                    | daf_contact_email_site12       |                                  |                     |
| 12. Will this site be housing requested data?                                                                               | daf_data_house_site12          |                                  |                     |
| 13. Site name                                                                                                               | daf_institution_site13         |                                  |                     |
| 13. Contact person                                                                                                          | daf_contact_site13             |                                  |                     |
| 13. Contact person email                                                                                                    | daf_contact_email_site13       |                                  |                     |
| 13. Will this site be housing requested data?                                                                               | daf_data_house_site13          |                                  |                     |
| 14. Site name                                                                                                               | daf_institution_site14         |                                  |                     |
| 14. Contact person                                                                                                          | daf_contact_site14             |                                  |                     |
| 14. Contact person email                                                                                                    | daf_contact_email_site14       |                                  |                     |
| 14. Will this site be housing requested data?                                                                               | daf_data_house_site14          |                                  |                     |
| 15. Site name                                                                                                               | daf_institution_site15         |                                  |                     |
| 15. Contact person                                                                                                          | daf_contact_site15             |                                  |                     |
| 15. Contact person email                                                                                                    | daf_contact_email_site15       |                                  |                     |
| 15. Will this site be housing requested data?                                                                               | daf_data_house_site15          |                                  |                     |
| 16. Site name                                                                                                               | daf_institution_site16         |                                  |                     |
| 16. Contact person                                                                                                          | daf_contact_site16             |                                  |                     |
| 16. Contact person email                                                                                                    | daf_contact_email_site16       |                                  |                     |
| 16. Will this site be housing requested data?                                                                               | daf_data_house_site16          |                                  |                     |
| 17. Site name                                                                                                               | daf_institution_site17         |                                  |                     |
| 17. Contact person                                                                                                          | daf_contact_site17             |                                  |                     |
| 17. Contact person email                                                                                                    | daf_contact_email_site17       |                                  |                     |
| 17. Will this site be housing requested data?                                                                               | daf_data_house_site17          |                                  |                     |
| 18. Site name                                                                                                               | daf_institution_site18         |                                  |                     |
| 18. Contact person                                                                                                          | daf_contact_site18             |                                  |                     |
| 18. Contact person email                                                                                                    | daf_contact_email_site18       |                                  |                     |
| 18. Will this site be housing requested data?                                                                               | daf_data_house_site18          |                                  |                     |
| 19. Site name                                                                                                               | daf_institution_site19         |                                  |                     |
| 19. Contact person                                                                                                          | daf_contact_site19             |                                  |                     |
| 19. Contact person email                                                                                                    | daf_contact_email_site19       |                                  |                     |
| 19. Will this site be housing requested data?                                                                               | daf_data_house_site19          |                                  |                     |
| 20. Site name                                                                                                               | daf_institution_site20         |                                  |                     |
| 20. Contact person                                                                                                          | daf_contact_site20             |                                  |                     |
| 20. Contact person email                                                                                                    | daf_contact_email_site20       |                                  |                     |
| 20. Will this site be housing requested data?                                                                               | daf_data_house_site20          |                                  |                     |
