### ISSUE TITLE
Scheduled Task Service (for Data Egress Loader)

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#382]
Add template for cron job task with the first use case of:

- Data Egress record loader needs to be triggered everyday to have the latest data as possible. This also allow each on-demand egress loader to be faster as it will have a lesser interval time to query.

**Comment by andrewpatto** [comment]
Happy for it to be even less that daily .. like every hour etc. I guess depends on the speed v cost of cloudtrail queries etc

**Comment by andrewpatto** [comment]
I mean the beauty of having a cron expression control it is that possibly it goes into the elsa config and the admins can control it
