### ISSUE TITLE
Change permissions probably doesn't work for PotentialUsers

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#396]
Just when inspecting the code - I don't see a code path for changing the permissions of Potentialusers.

Now, we might decide that it isn't possible to change the permissions of potential users (I don't have a complaint with that) - but in that case I imagine we need some UI stuff preventing it too.

**Comment by williamputraintan** [comment]
This is in the context of release user participant right?

Seems to be there and it is working as expected if we allow to edit the potential-user.

https://github.com/umccr/elsa-data/blob/c0e88a1a358570e16230191b8bc85e8a0134e013/application/backend/src/business/services/release-participation-service.ts#L257-L325

<video src="https://github.com/umccr/elsa-data/assets/61998484/e422dbaa-7eb9-4ef9-9e26-2c57e65588b1" />

**Comment by andrewpatto** [comment]
I think I was looking at the "non release" user API i.e. change user permissions. And I guess that is fine because we never want to grant permissions to PotentialUsers - until they become an actual user.

Thanks for checking.
