### ISSUE TITLE
Unify the descriptions of permissions for frontend

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#397]
Within the same frontend user dashboard folder - we currently have 3 separate string descriptions of each permission. All a subtly different to each other.

Can we unify the tense/language of all of these to a single set of constants (nothing fancy - just like literally a set of export const strings)

**Comment by andrewpatto** [comment]
I think you did this as part of your other PR @williamputraintan ?

**Comment by williamputraintan** [comment]
Right - it was supposed to close this ticket!
