### ISSUE TITLE
Add a new audit log for storing audit events that are *not* part of a release

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#40]
We need a mechanism similar to the 'release' audit mechanism - but for more general purpose events that occur *outside* any release context.

- [ ] login
- [ ] logout
- [ ] change user permissions
- [ ] admin level activities like load new dataset

**Comment by andrewpatto** [comment]
Currently there are two levels of audit log - ones specific to a release and ones that are general. The release specific ones are generally working and have an attached UI.

The general ones (where I'd put login etc) just have a db schema defined and nothing else. Need to flesh that out both in the backend Audit service and the APIs and a frontend standalone Log page.

We need to think about who is the audience for the general audit page - is this shown only to Admins? Is it filtered in some way to only show events I am involved in (if I am not an admin?). What other filtering is needed (date ranges / types?)

**Comment by andrewpatto** [comment]
This is part of a larger audit epic

**Comment by mmalenic** [comment]
Here's what I was thinking for this one:

This would be a new page in the navigation bar next to all the other pages (Users, Releases, etc), containing a table similar to the Releases audit logs, except with different information. I'm thinking that each user would be able to see the events related to themselves, with the admin user being able to see all events.

However, I'm not sure if this is the best approach. Should researchers or data owners be able to see a log of their own logins, etc - is this useful information? Or should this just be left to admins?

**Comment by andrewpatto** [comment]
Yep - I think that makes sense - I should be able to evaluate my own logins/logouts if I suspect someone has stolen my password etc.

**Comment by andrewpatto** [comment]
At which point though I might like to see all *my* activity across all releases.. so a "me" view of the world, as opposed to a "release" view of the world. Which I think is just a slightly different merged query across all the Releases..

Would be interested in the performance of this one - as we start to get to lots of releases.. maybe by default it is restricted to my "active" releases (though we don't yet have an inactive release concept)..

So even if they are restricting things to "one page" worth of logs - I fear it is going to have to do some serious searching across the entire audit database to even generate the first page unless we have good indexes

**Comment by andrewpatto** [comment]
I mean I don't *know* the performance of this one - am just wary that this might be somewhere that isn't self limiting.. so one to keep an eye on

**Comment by mmalenic** [comment]
>I fear it is going to have to do some serious searching across the entire audit database to even generate the first page unless we have good indexes

Yep, that sounds like a possibility. If this comes up, I think indexes would be a solution.
