### ISSUE TITLE
Wait cursors for Case box search aren't correct

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#408]
The case box search seems to have various phases - and on first startup (i.e when the database/indexes are cold) - takes a bit of time. Which is all fine - it doesn't need to be super high performance. But as per the attached movie - it is not clear to the user that the search is still in progress as this happens. Not sure what sort of wait cursors are appropriate and where (because it definitely seems to go through multiple phases) - but needs sorting out in some way.

https://github.com/umccr/elsa-data/assets/1973827/c744279f-e849-4e1a-944e-998f484602a3

**Comment by DoxasticFox** [comment]
Is there any way for me to get a hold of the dataset with 51 pages of cases in it? Or do I have to make a synthetic one?

**Comment by andrewpatto** [comment]
We can give it to you - its the one setup for AG demo (Its all synthetic fastqs) - but tbh - I've seen the exact same on our 10g and 10f ones - so I don't think it is the number of entries entirely. I think its more that when running EdgeDb locally its speed is substantially faster than when deployed to AWS

**Comment by andrewpatto** [comment]
I think possibly adding some artificial sleeps into the backend APIs for getcases and set selected etc would possibly simulate this just as well locally. We might do a different step on actually optimising the queries - this is more assuming they are slow..

**Comment by DoxasticFox** [comment]
I did this:

```diff
diff --git a/application/backend/src/api/routes/internal/release-routes.ts b/application/backend/src/api/routes/internal/release-routes.ts
index af72bbc..a502ad2 100644
--- a/application/backend/src/api/routes/internal/release-routes.ts
+++ b/application/backend/src/api/routes/internal/release-routes.ts
@@ -46,6 +46,8 @@ export const releaseRoutes = async (
 
       const releaseKey = request.params.rid;
 
+      await new Promise(f => setTimeout(f, 5000));
+
       const cases = await releaseSelectionService.getCases(
         authenticatedUser,
         releaseKey,
```

I think the result doesn't show the issue you're referring to:

https://github.com/umccr/elsa-data/assets/11529449/5ca4e276-568d-4606-8592-f084cb8faba5

It feels like a frontend performance issue to me---Like the search bar finishes rendering before the cases do.

**Comment by andrewpatto** [comment]
I might take this opportunity to move the Cases stuff from REST to TRPC
