### ISSUE TITLE
Add a bulk select/deselect using text files to the Cases box

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#439]
The cohort constructor will be the preferred mechanism to build lists of selected patients - but in the interim - we need a mechanism by which AG staff can use their existing techniques. This involves them building a CSV (TSV?) in excel with existing manual matching (doesn't matter as it is just one column I presume) of ids that they want to release.

We should allow them to drag this onto somewhere in the cases Box - and have all the matches specimens/patients be selected.

**Comment by andrewpatto** [comment]
I would think it probably needs an new TRPC endpoint that accepts a raw text file - and then the backend 'sets' the passed in ids (could be patient id or specimen id - I suggest we match to either).

I would probably suggest that this is not a 'toggle'.. or a 'replace set' of the existing cases. I think it probably should leave whatever is already selected exactly in place - but ensure that everything listed in the input file gets selected.

We could probably add a counterpoint "clear" - that takes from the file a list of specimens to 'unset'. (say they have been given an excel with the ids of 50 patients who have withdrawn).. they would first 'select all'.. and then drag on their CSV

**Comment by andrewpatto** [comment]
Happy for this to have any limits if they make things easier to implement (e.g. doesn't work with 1Gib text files). Possibly it takes 10- 20 seconds but we don't run it as a background task. 

This is an interim feature whilst we build out the cohort builder functionality.

**Comment by andrewpatto** [comment]
![Screenshot 2023-07-28 at 2 40 38 pm](https://github.com/umccr/elsa-data/assets/1973827/d7b74063-9c58-4d8f-b185-e0a50eb42c5c)

I mean doesn't have to any way be identical to this - but these are some thoughts I had as to where it might go

**Comment by DoxasticFox** [comment]
>This is an interim feature whilst we build out the cohort builder functionality.

In that case, should I prioritise CTRL for now? Would it be a good idea to skip this ticket and implement the cohort builder instead, later?

**Comment by andrewpatto** [comment]
I think they also have non CTRL related datasets that they still manually process - so it may not be until we literally do all the work on cohort building (beacon, ctrl, regular consent, etc) that they could use it in practice. I think this feature is small enough that it worth knocking over now and getting it into prod.

It also might be a feature we leave in - even if we do have cohort building.

**Comment by DoxasticFox** [comment]
> I would think it probably needs an new TRPC endpoint that accepts a raw text file

> Happy for this to have any limits if they make things easier to implement (e.g. doesn't work with 1Gib text files). Possibly it takes 10- 20 seconds but we don't run it as a background task.

How many specimen IDs can be in a CSV? A CSV containing 10 million sequential integers is about 100 MB. Processing that client-side, in the browser takes a few seconds.

Instead of making a new endpoint to accept raw files, I was thinking of modifying [this](https://github.com/umccr/elsa-data/blob/18adc5e53858487f3c39d127b8ba831078291b5d/application/frontend/src/pages/releases/detail/cases-box/patients-flex-row.tsx#L70-L83) endpoint to accept literal specimen IDs. Seems a bit DRYer than a whole new endpoint, as long as doing that would still meet our requirements. What do you think?

**Comment by andrewpatto** [comment]
It will need to work with patient identifiers (and also probably specimen identifiers). So as a method call we are proposing the backend operation will be like?

releaseKey: "..."
op: "add"
value: [ "BART", "NA128787", "345-345-234-234-453-453" ]

where the passed in values can be either a
specimen edgedb id
a specimen identifier value (from its identifiers array)
a patient identifier value (from its identifiers array) - (which will in turn select all sub specimens)
(possibly a case identifier value (from its identifiers array) - (which will in turn select all sub patients/specimens)


Just some top of the head thoughts - we will need some extra backend to check that we don't manage to "add" the same specimen more than once. I mean that probably automatically is baked into our Edge model that each specimen can only be "in the release" once, but would be good to have a test confirming the correct operation of that (as if we are talking about allowing the specimens to be added to be named in multiple ways)

**Comment by andrewpatto** [comment]
If you are handling the recursive add/remove (i.e. the ability to specify identifiers at the patient or case level) - then possibly the values accepted should be

specimen edgedb id
a specimen identifier value (from its identifiers array)
patient edgedb id (which will in turn select all sub specimens)
a patient identifier value (from its identifiers array) - (which will in turn select all sub specimens)
case edgedb id (which will in turn select all sub patients/specimens)
a case identifier value (from its identifiers array) - (which will in turn select all sub patients/specimens)

If the backend is able to handle all of those - then we can improve the frontend UI to allow the patient and case checkboxes to be live (at the moment they are read-only)

But understand if you don't want to tackle that in this PR

**Comment by DoxasticFox** [comment]
>So as a method call we are proposing the backend operation will be like? [...]

I hadn't considered patients' external identifiers, actually. I was just thinking about using the specimens' external identifiers for everything. I assumed there was a DB constraint which made a specimen's external identifier uniquely refer to its corresponding DB entry. Though I've taken a look at the DB now, and I don't see a constraint like that. If I understand correctly, it's possible for one external identifier to refer to multiple specimens and/or patients. Realising that makes it less attractive to jam all that functionality into one endpoint.

I think there's constraints for the other stuff you mentioned though. But, yes, will add tests.

**Comment by andrewpatto** [comment]
Yeah whilst in reality I would hope the specimen and patient external identifiers are unique - that really is up to the dataset creator so we can't enforce that. 

The CSVs that AG want to use will only consist of patient identifiers (AG study ids). We derive specimen ids to refer to the underlying specimens (from the filenames) but that is not how AG have a record of them

**Comment by andrewpatto** [comment]
(sorry yes re-reading the initial ticket description I didn't make it clear it needed to work primarily with patient level ids)
