### ISSUE TITLE
Check last remaining REST audit event routes

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#453]
There are two REST audit-event routes that I don't think are used anymore.. or if they are used - should be moved the TRPC.

Feel free to be ruthless here - happy for things to be removed at the API surface - and we put back in later if needed
(even if there is some backend functionality left in).

The other release/external REST routes are needed as REST because of the way HTTP works - but other than them I'd prefer everything TRPC

**Comment by mmalenic** [comment]
I'm pretty sure these are unused, but I'll double check.
