### ISSUE TITLE
Whole case select/unselect grays out the entire page

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#469]
When changing the checkbox of individual samples - only the single case row is "grayed out" during the operation.

However, when changing the checkbox of a case - the entire page of cases "grays out" during the operation. Wondering if it is possible to get it to behave the same as the sample checkbox case?

**Comment by DoxasticFox** [comment]
I haven't checked, but I think the entire page grays-out when uploading a CSV too. So I think that's the correct behaviour; users should be prohibited from uploading a CSV while (un)checking case or sample checkboxes

**Comment by DoxasticFox** [comment]
So, for this issue, I think the fix would be to change the behaviour for the specimen's checkboxes rather than the case's, right?

**Comment by andrewpatto** [comment]
For uploading the CSV that is fine - as visually it is showing that the change is applying to the whole set of cases (which is true)

For the sample (and case) I meant more visually that it looks best if the "grayed out" *only* affects/refreshes the single row - as that is giving a visual indication of the scope of change. So changing the checkbox of one case really is only affecting the background/server state of *just* that checkbox (and its encompassed samples) - so graying out just the single table case row reinforces that.

As it is at the moment - the user is given the impression that toggling a case checkbox is altering some larger state.

I realise in the backend it is all possibly going through the same API - and possibly this is more difficult than it is worth - so just look into it and see if it is easy
(its just a react-query / refresh state kind of fix I think)

**Comment by DoxasticFox** [comment]
Makes sense

I'm working on something else right now, but I'll pick this ticket up soon. Hopefully towards the end of today
