### ISSUE TITLE
Add a htsget manifest download as TSV

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#474]
In the same spirit as other sharers - possibly add a TSV that downloads object URLS - that are htsget urls

**Comment by andrewpatto** [comment]
Will see if I can do this at the same time as I do the access point sharer TSV

**Comment by andrewpatto** [comment]
This was progressed a bit but needs to be correctly fleshed out what goes in the columns

**Comment by mmalenic** [comment]
Just confirming, this one's still incomplete?

And by TSV download, this is the button being referred to?
![Screenshot from 2023-12-14 14-08-46](https://github.com/elsa-data/elsa-data/assets/53923960/901f4e65-d19a-440b-8cca-3ada6ae81930)

**Comment by andrewpatto** [comment]
Yep that's the button - and other than a *very* simple initial implementation - this is definitely incomplete.
