### ISSUE TITLE
Emails templates not found via dev cloud install

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#482]
![Screenshot 2023-09-15 at 12 16 30 pm](https://github.com/elsa-data/elsa-data/assets/1973827/96f697b4-315e-48ff-8ff4-fb30aa1f10b6)

I've enabled SES on the dev deployment for the first time (and given the deployment SES send etc).

Have an issue now with the paths not being right. Probably could be a setting that is needed - but given I do not want to alter the templates it probably should work out of the box.

**Comment by andrewpatto** [comment]
I see in the docker image that the emails folder *is* being put into the base elsa docker image

```
COPY --from=app-builder /build/backend/emails/ /a/emails/
```

**Comment by andrewpatto** [comment]
I think at a minimum we need to have a config option that lets the root folder be specified - so I'll do that

**Comment by mmalenic** [comment]
Ahh, yes I think I copied this over wrong. The email templating expects templates to be under an `emails` directory, so maybe it should be something like: `COPY --from=app-builder /build/backend/emails/ /a/server/dist/emails/`. Otherwise it's possible to specify the directory: https://github.com/forwardemail/email-templates#options

**Comment by andrewpatto** [comment]
All the other things that are settable (logo etc) have the ability to set an absolute path in the config - so I've just added one of them. I mean at some point - when we have "locales" and "emails" and all sorts of things - perhaps we need to re-consider where we "start" the server from. Or as you say - maybe decide where we place these folders

**Comment by andrewpatto** [comment]
Re-opening. Even with root path set it doesn't seem to be working correctly.

TBH - looking now - it is looking for `template.pug` - but this is not the name of any of our actual templates?

**Comment by andrewpatto** [comment]
So template.pug isn't mentioned anywhere in our entire source base - so not sure what is going on. Can you investigate @mmalenic
