### ISSUE TITLE
Get egress stats working with access point objects

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#494]
With the newer access point sharing - there is no release identifier in the cloudtrail entry. However, there will be an access point bucket name that does map back to the particular release. Need to teach the egress routines to understand this.

Currently (understandably as access point sharing is new)

![Screenshot 2023-10-10 at 2 20 28 pm](https://github.com/elsa-data/elsa-data/assets/1973827/801b84ea-2a99-4bb6-97ad-1502171a4318)

**Comment by andrewpatto** [comment]
The Uom demo account has a cloudtrail lake with events of access point Get occurring between 2pm-3pm on October 10

**Comment by andrewpatto** [comment]
I think currently all the mapping from Release to the access points created lives in the actual installed CloudFormation outputs. Which would limit egress tracking to whilst ever the access point is live.

So its possible we might need to add some extra database fields to track this info as part of the Release activation?

**Comment by williamputraintan** [comment]
Yes, possibly put this in the audit records? I guess the copy-out is also out of track within the releaseEgressService?

**Comment by andrewpatto** [comment]
Can we make a different ticket for copy-out - but yes that would be good if that was counted as well (it at least shouldn't cause _problems_ with the egress code).

I think I'd prefer to keep the information out of the audit infrastrucutre (even though it is used by the audit stuff - those fields are more "sharer" or "activation" data)

**Comment by williamputraintan** [comment]
I am thinking of the `Data Sharing Control` pane is locked when the release is activated (as if like the cases) and could keep track sharing method for each activation?
