### ISSUE TITLE
AG dataset index import mechanism

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#66]
Following up on the initial import mechanism from AG bucket to Elsa (#43 and #58), there are more things need to be done to completely import AG data to Elsa.

- [x] Mechanism on registering new Flagships. 

  Elsa would need to know each folder/prefix in S3 belongs to which dataset, by this there might be a mechanism of registering a map between prefix and dataset record. This process could also be the [initial creation](https://github.com/umccr/elsa-data/blob/26a597614fadbd9b53cbbe02da576c01f2d916c1/application/backend/src/api/routes/dataset-routes.ts#L83) of the dataset record for the files to be associated with.
 
- [x] Handle file deletion

	Some data might be requested to be deleted from AG bucket, ideally this should reflect on EdgeDb. Current implementation is again printing it to the console, probably this should be deleted and a popup warning shows the list of files to be deleted? Also to think, what happen to current grant access for the deleted file?
 
- [x] Complete the data model

	Some of the entries are trios (_mat / _pat) so these should go into a 'trio' case family group

- [ ] Get the Files to be included in SubmissionBatch objects that correspond to each folder

- [ ] Handle mysterious/incomplete submission.
  
  Some data may have pairs located in a different key-prefix/directory, ideally this would still be a valid a location but the current script would only consider pair from the same location. These skipped file is only printed in the console and need to be change so it could be inserted to EdgeDb appropriately.
  Note: If considering to find pair from different location, there is a chance that filename could be duplicated as part of reanalysis. This would be hard to identify which pair belongs to which. (Ref: https://trello.com/c/NFSr0Gjq)

- [ ] Decide on how/any phenotype information can come across into Elsa Data and where to source it

	Even basic things like "sex" and "age at sequencing" are not available to this Elsa Data import as it runs purely off S3 genotype information. What can/do we want to do here?

- [ ] DatasetPatient is no longer consented with the study. Current AG implementation is removing all related patient datas. 

	Do we also need to remove the patient record from `elsa`?  Perhaps another flag to show if patient is no longer available? A consent system exist in Elsa should this be enough without any other flag/deletion? 
	
	~ To be discussed with AG

**Comment by williamputraintan** [comment]
Proceeding with this issue, wondering if the following solution is suitable:

> Mechanism on registering new Flagships.

Having a button in `Datasets` page that will show popup/redirect to a page to fill in forms for a new dataset? The form including to fill Dataset URI, S3Bucket prefix, CoudTrail (if any)

>  Handle file deletion

This might be a straight deletion from edgedb when sync detects deletion had happen, and the API response would just show any deletion file list that will also be shown on the UI. At this point S3 file usually no longer have the data anyway, so might just delete it here as well.


cc: @andrewpatto

**Comment by andrewpatto** [comment]
I'm thinking less UI for the registration.. how about a config file?

We have config settings for super admins

```
superAdmins: {
    doc: "A collection of users with super administration rights i.e. the ability to alter other user rights",
    format: "user-array",
    default: [],

    children: {
      id: {
        doc: "The user subject id",
        format: "*",
        default: undefined,
      },
      email: {
        doc: "The user email",
        format: "*",
        default: undefined,
      },
    },
  },
```

We define the ability to specify 'flagships' array - and come up with a little schema of all those fields you mention..

Then we can just make a config/flagships.json5 for inclusion in the deployed docker image..

**Comment by andrewpatto** [comment]
The concern for deletion is more that that sample/file may already be included in a dataset that has been released..

So deleting them out of the index may be a significant event as far as the 'release' goes.

I mean I take your point that the file is no longer there so the researcher already has some problems!

**Comment by williamputraintan** [comment]
> The concern for deletion is more that that sample/file may already be included in a dataset that has been released..
> 
> So deleting them out of the index may be a significant event as far as the 'release' goes.
> 
> I mean I take your point that the file is no longer there so the researcher already has some problems!

Hmmm, how about (maybe for now) having a boolean `isAvailable` just to distinguish which data has been deleted or not?

**Comment by andrewpatto** [comment]
So a flag on the actual FIle object? I think that's a good plan..

**Comment by andrewpatto** [comment]
Consdering this actually closed - we'll do a new PR for new approaches to dataset loading
