### ISSUE TITLE
NavBar Hamburger button not working on small screen

### ISSUE THREAD

**Issue by williamputraintan** [umccr/elsa-data#67]
Context:

<img width="633" alt="Screen Shot 2022-10-17 at 7 14 51 pm" src="https://user-images.githubusercontent.com/61998484/196124564-2b7042dc-0921-4d0d-b21c-5b06d789df60.png">
(Button does not work when clicked)

**Comment by andrewpatto** [comment]
Yeah the hamburger came with the Tailwind templates I was using - but I did none of the effort to actually make it do anything! (in fact I may have simplified the layout to make it definitely not work)

A good one for noting thanks
