### ISSUE TITLE
Create a mockup/trial model for how CloudTrail accesses can be rendered inside Elsa

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#76]
The CloudTrail logs are able to be queried looking for a subset of entries related to each 'release'.

Whilst cloudtrail is excellent for actual audit (like a legal investigation) - the data is probably better situated inside Elsa where it is accessible directly from users/data custodians (who in general won't have access to the AWS backend)

We need to decide on what data we want to bring across (all? some? summarised?) into the Elsa Data db and what level of functionality we want to provide to users.

Some considerations
- log size? We don't want 5 Gib of cloud trail data causing other aspects of Elsa Data to be slow/inefficient..
- UI functionality - what is actually going to be useful to spot outlier behaviour?
- can we make a model that works with all clouds - not AWS specific..

This ticket is just about getting some early thinking - and perhaps a UI mockup of what might be possible to stimulate some thinking..

**Comment by andrewpatto** [comment]
Would prefer more on the demo/mockup side if needed - rather than all the plumbing of how the logs will be brought over from CloudTrail etc

**Comment by williamputraintan** [comment]
Moving this feature to be more production manner, wondering if the initial attempt would suffice to make more plumbing to use AWS CloudTrailLake query?

One to discuss, wether all CloudTrailLake event will be stored directly to edgedb (as the current approach ), store in a summarise manner (maybe daily?), or other idea on where to store raw logs so it edge doesn't get too much records for egress data.

**Comment by andrewpatto** [comment]
So currently there is a 1:1 between cloudtrail entries and edgedb records? (but presumably not *all* the cloud trail data for matching entries comes across?)?

I think for the general S3 presigned urls that that is a sane amount of data..

I worry about something like htsget - where there might be continuous action across months.. (I mean we might source the data direct from htsget logs and not cloudtrail) - but this possibly points towards more of a daily summary format?

**Comment by williamputraintan** [comment]
> So currently there is a 1:1 between cloudtrail entries and edgedb records? (but presumably not all the cloud trail data for matching entries comes across?)?

Sorry, I meant just the one that has a matching `x-releaseId` from the presignedUrl. I am just thinking if this could still be a few number of entries if there were multiple attempt (if decided to download in a multipart download scenario).

**Comment by andrewpatto** [comment]
Yes but even for those that match x-releaseId - I presume we don't bring across the entire CloudTrail record?

**Comment by williamputraintan** [comment]
Yes, just the matching ones.

**Comment by andrewpatto** [comment]
But the full audit record (*all* the AWS cloudtrail fields).. or just a few fields?

**Comment by williamputraintan** [comment]
Just a few fields. ([example](https://github.com/umccr/elsa-data/blob/7b6d8c94cdc45cd8c2068f4970ec0d8af04209ba/application/backend/src/business/services/aws-cloudtrail-lake-service.ts#L119-L152))

I think that is the most relevant field. I don't think other cloudtrail fields is necessary?
