### ISSUE TITLE
Revisit React upload component used in AG Redcap DAC import

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#81]
We have used a drag-drop upload CSV convert component in the AG DAC upload.

Its not great however - looks not good, does too much (inbuild papaparse).

Should try to find a better one and put that in

**Comment by andrewpatto** [comment]
Specifically the things I don't like 

Its currently quite ugly..

The 'uploaded' file hangs around - whereas I think our use case is more 'upload then trigger dialog'.. so it should essentially reset UI state on finish.

The CSV parsing is kind of mashed in with the React code

**Comment by DoxasticFox** [comment]
>does too much (inbuild papaparse)

This isn't intrinsically a problem, right? Is the root problem that react-papaparse is too big (in bytes), or is it something else?

**Comment by andrewpatto** [comment]
No size isn't a worry,

it was more it just felt a bit clumsy as a React component - I think that comes through from papaparse itself being a bit old school (I mean super good component and well tested etc but pre-dating promises etc). It just felt a bit strange (and UI didn't look great!). But others may differ - its perfectly functional - so this is not high priority.

I was just thinking once I'd finished that perhaps having the CSV parsing split from the UI - might mean we could get a more on point one of each (which was what I was intended first off until I saw this combined component and thought I'd give it a shot).
