### ISSUE TITLE
Add a clever 'View' audit entry when releases are viewed

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#90]
I would like a 'read' audit entry that allows users to go into and out of 'releases' - but that doesn't generate a huge quantity of meaningless entries.

So looking at some way that 'read' entries are generated - but then automerged somehow (nightly? in a separate ProposedAuditEntry table?) so that if a person went into a release 10 times over an hour - we just get a single audit entry
(Viewed - duration 1 hr).

We will obviously need some time limit such that we can automatically 'finish' off an audit entry - as there is no explicit point at which someone finishes reading a page (unless they log out)

**Comment by andrewpatto** [comment]
As a note - at the moment there is _no_ auditing of 'read' activity in Elsa. Only operations that mutate state are audited

**Comment by andrewpatto** [comment]
This is less of a concern - than in say an EHR system - as there is really no inherent PII viewable just by wandering around the UI or APIs. The data it protects (i.e. the BAMs) is the PII data.
This might change if we bring lots of phenotype data into the db?

**Comment by andrewpatto** [comment]
I think we could possibly do this with a "have I already made a 'view' audit entry for *this* person in *this* release in the past X minutes.. and if the answer is true - then we don't make another entry..

However, I think we'd want that mechanism to be pretty efficient - how efficient I don't know?? A simple in memory cache in the AuditLog service?

**Comment by mmalenic** [comment]
Do you think this would be better as a "release" audit event, i.e. an audit event on a given release, showing that a user has viewed it. Or, as a "user" audit event, i.e. an audit event for a user, showing that they have viewed a release?

**Comment by andrewpatto** [comment]
I mean it is both - though that is true of all activity performed in a release (which is broader question then about the modelling of the audit events, I never quite got the exact demarcation between release and user audit events..). 

I think primarily this is about the fields/data in a release - so in the same way that "update field" is an audit event in the release, "view" is also primarily a release audit event

**Comment by mmalenic** [comment]
I think the difference in practice between the user and release events is probably just where/how they are shown, e.g. whether its in the release audit table, or the general audit table under the "user" checkbox, although I agree that it is both in a way.

I think in this case it makes sense for it to be a "release audit event", because it applies to releases, like all the other audit events on a release.

In that sense then, I think release audits should in general be audit events that apply to a release, and user audit events be audit events that *only* apply to a user.
