### ISSUE TITLE
Look into data ownership relationships in Edge Db to better support cascading delete

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#94]
I think it would be good if we had clear 'ownership' relationships between objects in Edge Db.

For instance - the Consent statements of a patient belong to a Patient - so don't make much sense if they are retained after a patient is deleted. I believe it is possible to express some of this in the edge db schemas.

I think the end goal is that data can be systematically removed from a db - with broad delete statements. So for instance - if there was a 'bad run' noticed (sequencer machine was contaminated say and this was discovered a month later).

We might say that the operations are the delete/alter any Dataset using those Artifacts.
Then delete the Run itself.
With the expectation that all files uploaded by the run are also cascade deleted.

**Comment by andrewpatto** [comment]
This might be a good ticket to do immediately after we go to native Edgeql queries.

Because part of the 'db-test' layer I think will be to execute a bunch of native edgeql queries to confirm they work.

And at the same time we could road test some cascade delete tests - and confirm that things are really removed

**Comment by andrewpatto** [comment]
Part of this might be to draw a bunch of object ownership heierarchies? In draw.io for keeping in the repo? I know I did an Lucidchart of the initial edgedb tables - but perhaps we can represent alternatively in draw io?

**Comment by williamputraintan** [comment]
> Part of this might be to draw a bunch of object ownership hierarchies?

What is the idea of representing this? Something like a UML diagram?

Or something simple as below. 
<img width="100" alt="Screen Shot 2022-12-09 at 6 39 04 pm" src="https://user-images.githubusercontent.com/61998484/206650075-f5c8c58e-527c-497a-9931-d52cdc461c24.png">

**Comment by andrewpatto** [comment]
Yes something like a UML (I mean UML has the concepts of aggregation/composition etc - which is kind of like 'ownership'). 

I mean your diagram is simple enough and I would be happy with something like that (though it is wrong?) - I mean the relationship between DatasetCase and Dataset is not at all the same as the relationship between Release and Dataset (or were you just showing an example of the diagram and not the content?)

**Comment by williamputraintan** [comment]
Yeah just a draft on the idea of how it would look like.

**Comment by andrewpatto** [comment]
Excellent - yeah something simple like that.. no need for actual 'fields' in the boxes.. just high level Class names for the moment.. and proper aggregation and composition etc.
