### ISSUE TITLE
Frontend can seem to run ok even though login credentials are expired

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#96]
If you leave the frontend logged in overnight - the next day - you will be able to navigate around and press buttons - but effectively you are not able to do anything because every API request will fail (token expiry).

You are still 'logged in' because the cookie/token still exists - its just no longer useful.

We need to get the frontend to detect this and bounce the user to the login page or something? Not sure how best to handle this - open to options?

- every 5 mins some background javascript that checks the validity of creds and 'logs out' if invalid?
- the frontend detects the specific API results that come about from expired credentials a puts up a message?
-

**Comment by andrewpatto** [comment]
I'm only noticing this when I log into the deploy Elsa - so presume it is symptomatic of a shorter CILogon token validity?
(should investigate)

**Comment by williamputraintan** [comment]
Just another idea, maybe put an expired time for the cookie? Say for each window refocus or maybe every click on the window, we would check if cookie still exist if it doesn't redirect to login page.
