### ISSUE TITLE
Make email a first class compulsory User property

### ISSUE THREAD

**Issue by andrewpatto** [umccr/elsa-data#97]
There are various TODO's throughout the code where we say "should save email address". So whilst we currently save the users

subjectId
displayName

we didn't save email because I didn't know if we should make compulsory. But I think from experience now that we should insist on an email address.

Though we should do this in conjunction with CILogon, where different email addresses can assert the same subject.

Anyhow - we need to work out what to do about emails.

**Comment by williamputraintan** [comment]
> different email addresses can assert the same subject.

I think this is a bit complex of having the same CILogon but have different email. If this email is outside CILogon, I suppose we would need an OTP kinda verification to make sure the right user could claim that email?

Maybe for now we could safe to assume, the email listed for sharing must be an institution email (same gotten from OIDC)?

**Comment by andrewpatto** [comment]
I'm happy for the moment with institutional logins as you say.. but for instance - I think if someone adds an ORCID linked identity to their CILogon (so will be a single consistent subject) - but then does a login flow via ORCID login, I'm not sure *any* email address is asserted in the OIDC flow.

Maybe we just need to do some experiments to get a handle on what currently happens.

Can you add two extra logins to your existing unimelb CIlogon user - and then do some logins and see what is actual asserted in the CIlogon claims?

![Screenshot 2022-11-21 at 10 18 44 am](https://user-images.githubusercontent.com/1973827/202931995-eb234892-e114-4369-bbc7-62f066e732a0.png)

**Comment by williamputraintan** [comment]
CIlogon claims does assert email address of this what you meant.

> Can you add two extra logins to your existing unimelb CIlogon user - and then do some logins and see what is actual asserted in the CIlogon claims?

Do you mean merging 2 CILogon logins?

**Comment by andrewpatto** [comment]
Yes - CILogon allows you to have multiple logins associated with your cilogon identity (the "Link another account")

So if you set up your william user to have 3 identities (one unimelb, one google and one orcid) - we can then simulate what is the difference of claims when each of those 3 actually do the login

**Comment by andrewpatto** [comment]
(I'd merge *my* accounts in cilogon, but I need to retain one admin account separated from unimelb one for testing)

**Comment by williamputraintan** [comment]
> CILogon allows you to have multiple logins associated with your cilogon identity (the "Link another account")

Sorry, but does this option doable from the CILogon UI or config itself? Or require somthing like [globus](https://www.globus.org/) to link accounts?

**Comment by andrewpatto** [comment]
Go to https://registry-test.biocommons.org.au/registry/co_dashboards/dashboard/co:8 and you should be able to see the menu from the screenshot above
